[tasks.test]
description = "Run nextest"
install_crate = { crate_name = "cargo-nextest" }
command = "cargo"
args = [
    "nextest", "run",
]

[tasks."test:insta:review"]
description = "Run insta review"
install_crate = { crate_name = "cargo-insta" }
command = "cargo"
args = ["insta", "review"]

